## Import Modules

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

## 資料路徑跟來源

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# DATA_PATH = "drive/MyDrive/ESun-Competition-2023/dataset_1st/public_processed.csv"
# CUSTOMER_DATA_PATH = "drive/MyDrive/ESun-Competition-2023/preprocess_data/output.txt"

data_path = "data/training.csv"
test_data_path = 'data/public_processed.csv'
CUSTOMER_DATA_PATH = "preprocess_data/output.txt"

DATA = pd.read_csv(data_path)
TEST_DATA = pd.read_csv(test_data_path)

In [4]:
DATA

,txkey,locdt,loctm,chid,cano,contp,etymd,mchno,acqic,mcc,...,stocn,scity,stscd,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk,label
0,1c09727c939eb69ead2a4ce4072b8aa18992a64f01fcb4...,46,101812,84d2dc85d4da6a7fa284a11a4290d7e9a969163dcb4d82...,3dd5bf1e29e5e0baa789ce692fe5dbd34ff05173acf351...,5,1.0,cad752c5d05d2bdcc30d64fa4e68404c2d1f7be5d14d52...,8f6b3ff512a001e0d1988c6cd888ef8c74112fb71117e5...,375.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,1529,0,0
1,2043f245a93bc6328dac964d6dbc89f13a0346062c194d...,17,85509,9a8cf5d0afd729cb7876f6b3172152c7c9c6fabd40515c...,8cb13f9b38c7bbc02d210e580dcbbcbb6c95bf18bc3320...,5,8.0,4356c6642ef6e837543b577c7ee3ffa92b4b8fcfb57254...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,282.0,...,0.0,15759.0,NaN,0,0,8.0,70.0,101,0,0
2,e4853710290a8409279f3279f8032ae670824bd19aa173...,44,212641,dcc1389a5765d6f53152cf85970fbe78a83fd3d1c299b0...,1ec32868e5e1d5ff8df56737c2a91326cbfe3364382de6...,5,4.0,5b7eff061f8896aac4339ea35c25f8bb956a43bc486460...,8f6b3ff512a001e0d1988c6cd888ef8c74112fb71117e5...,288.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,116,0,0
3,74d811b1dbc28b22b73ba2c79bb6033791d913b6d27a25...,42,102702,577f2329d1eccd59ba0abaf6113bb78dcd575badcbc57f...,4359dca1ac6a835eceb2bc0dd6b0b710f030c3499126e9...,5,1.0,cad752c5d05d2bdcc30d64fa4e68404c2d1f7be5d14d52...,36684976be1f529e6e2a32c9edab4cf8e364b2b916ae2c...,375.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,1683,0,0
4,68ca182343969d429d79a34e532bc1ca7a3cc032c2ad81...,31,185737,fff6b4126c40620b1fbb11d4de02cd67b9e95071caa40b...,a3837f2905383f235a72679482c5f02e40f2a8ca29750d...,5,5.0,50d5b02ce3fc88723438c2a29cfdb04be4a1a11280ddb6...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,406.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688521,fe5788aae7affa13a3946608670d7cdb9b4cde44f8f2cf...,14,84737,a894ea5eaf2c114231806da124f9d422b2c74653f071ec...,4616fbb5e28fbf86012461fc98652f51af00d2226aa634...,5,4.0,3c31ae50e4d36fe64a518a2c8109d14dd8d6b3a08edc92...,5f9c23caf7da7e1cf1e53ff9eab71dde3cfd72819e5210...,282.0,...,0.0,15759.0,NaN,0,0,0.0,70.0,49,0,0
8688522,8a2b5b7ba4443c311f06be147e42e7493735ae203c48ba...,23,105923,e3ee9fcf2bbabdfb2a4e6a7dfca046f1597888a8ebc3d2...,29e5be6d2bc0f3e539f13675c3faada5f07afb6f6df40a...,5,4.0,f56737b0e28217d7958e7ef135df60a5a02451c61596ef...,8f6b3ff512a001e0d1988c6cd888ef8c74112fb71117e5...,276.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,4018,0,0
8688523,15a9ef847ce3702a176abfaceedf9a22a328e27a0c99a9...,23,141030,85a538fe0cb00a82ebdb948f1a8b45bfea5005dfcf7dcb...,2990660b8172986c57c793f16bb565ae29cd7572b50f05...,5,4.0,5f5906af767850a3d99fee5fc7ec9025467c4f9d9c8070...,2fea345d14a69774026f3de93f5e3313219363d54e07b1...,272.0,...,0.0,11380.0,NaN,0,0,6.0,70.0,314,0,0
8688524,2ed4454b4fcce6b9f98c3c22a1df941f03beb14bce94ea...,10,120209,1dd744fc7ca8249f3eb54514530bd9c242d338421ef819...,fca665553fe576b40984abe18261056736b923c3310f1d...,5,5.0,c795cb82dae8d6605d4856d4f2fa58cf1b0e158457fab8...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,272.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,225,0,0
8688525,eb17de9aad63d3baa82eb2c59c3760287a53d7c9a57588...,4,15317,b03f85ac9d0571375e245a609c062100e9caa5a5619d9f...,062a52ca16c65c39f3f4f42d6f006f14cd2f6530379f2a...,5,8.0,bbc76c23062521522aa53f2e9b710a92ed4a694019003f...,5d2fbec5d1f0d08c596cbfb0a295c4832a7eb859f295b8...,309.0,...,0.0,15759.0,NaN,0,0,6.0,70.0,166,0,0

In [5]:
TEST_DATA

,txkey,locdt,loctm,chid,cano,contp,etymd,mchno,acqic,mcc,...,flam1,stocn,scity,stscd,ovrlt,flbmk,hcefg,csmcu,csmam,flg_3dsmk
0,a2c1209018e4e52e04f6fabb48f05f1b8bc09dc838ff6c...,56,105157,d6d145d0d058e3f63b9ec421cf9e1543b0c3e059d18c2c...,9c454e0cf3680075b0382394ca59b00ee9435fd829da29...,4,1.0,8be206f97d10b57a46ea0ef5527155a0f9b48d16255b70...,2a608b081c09492bd2bc96d7def5371c4bc9cabf324a98...,272.0,...,1349,0.0,15759.0,NaN,0,0,6.0,70.0,1349,0
1,16c4880500059e01553789be11bbb50753b7acaae7b95b...,56,185520,b599fb83473599fa2df4a04136a668c28df7914293f1da...,9f097cba6a70333c906904ebaad438356cf75b6abf5dd4...,5,8.0,dd280b4f35a02701142ba7de47abb9736deca3eed86474...,46f63555d29f177290dfe20e989146fb033e453f1d5ff3...,320.0,...,306,0.0,13451.0,NaN,0,0,6.0,70.0,306,0
2,623c56be3bee87724e3d119c271d9ed098eeda84233183...,59,102312,8de197129150d454df1639e9743c1aa11b1c1122a2010c...,439691cb167b272661c2eb9073124f5d422f446b0f92fb...,5,1.0,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...,494.0,...,20,0.0,15759.0,NaN,0,0,NaN,NaN,0,0
3,250da12187059cf6e3a3066656a2919d08ceb8207efd55...,58,230138,f9cbad08a76f1dd9736a4fc51255eb55637ec0a417a406...,992679b728784192c17e90939918cbfae32ad1222fad26...,5,5.0,bd2b3523b4ecd652445b75ea7583c92f6f02af3971251b...,70dac5b1dfde828f556a93321a649df72891db35430588...,272.0,...,8339,42.0,12381.0,NaN,0,0,6.0,70.0,8339,0
4,4b268e0da036f44cbbb056ddfac6a28ea336d9cf299843...,59,101937,27d235e691a425098f291105f78f9877e05bb75e1f132b...,763fd2a91420f9b632c378ca82ff9e318851fa1964cbba...,5,5.0,156987f72b8993b8c5a898fa76f3b8e6454e10e18aa238...,89b1654aaef0b65b1868004cfdce2dcbb67f15b7fba535...,217.0,...,163,126.0,14786.0,NaN,0,0,6.0,68.0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600177,741a391b2c2114491d1d18acb1a892341b9280e1e3529f...,56,93445,2682f330b73282799bf3ef541bae705d514c5db39294cf...,22140589fb47e13001536d7bb184c49787fa8e48b1428e...,4,1.0,d5375a34f62be5545856ecffe8b6351298d443081845b9...,13624921218432873e0cfa1966e41376844b387695a0ee...,231.0,...,96,0.0,16117.0,NaN,0,0,6.0,70.0,96,0
600178,76f613595631fb35938bf10f5b7abe3f60a3d34ccf5f44...,56,145420,dda3e682f516da803061ac325237915fcda57c6c02295a...,0e021870d9c50e284e8d792b3834579acdac17972d5932...,5,5.0,d3c72a48a61829f273204d8ea5edba4172fb49370aa9e6...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,375.0,...,2017,0.0,15759.0,NaN,0,0,6.0,70.0,2017,0
600179,c32e846a4469e4869e2df8f8e160fba4e829b6beebb44d...,58,3400,4f745fe0a5c2bd94c7e5425b5c9f46ab2a9e49aff504b7...,477a9201460a4201b9599ee8e85e9c4ed0586c8e18fac4...,5,1.0,45b6cb170af96950ffd009b6275bb22f5f5b052687d237...,839aa8d49064459ddd81fcb39ca4e3420577b8faa0db91...,406.0,...,33,126.0,10300.0,NaN,0,0,6.0,70.0,33,0
600180,d641cd25a830de759cd55b4a643d71eadb770bc917aed3...,59,134901,c9f4c0549ba75e96ab85f3638f3b83167757d6716c7a6b...,4e9975c655afe0fcf6f226c49e50082ec5146584cd1ef9...,5,4.0,02374f9c035510cd74701576d1246a65895db64ebf8021...,8f6b3ff512a001e0d1988c6cd888ef8c74112fb71117e5...,288.0,...,1796,0.0,15759.0,NaN,0,0,6.0,70.0,1796,0
600181,301d0262bdd594a886446ddca09b4a21bef51dddf9618a...,56,220238,8f12d0d4eda2578df72a958e532d627996e5f067ad7b48...,6139394400615fea7f8b06cf2891fe82f69594081a099c...,5,8.0,e9fdf703d8d347bbdd35e1300392e101d1a28b7bb492fd...,379166ff4a62dac343b4b734188aa618716cc496e48b65...,276.0,...,239,0.0,15759.0,NaN,0,0,1.0,70.0,239,0

## 人工移除特徵

In [6]:
# by intuition
removed_feat = [
    'cano',   # 卡號
    'mchno',  # 特店代號
    'acqic',  # 收單行代碼
]

DATA = DATA.drop(columns=removed_feat)
DATA = DATA.drop(columns="txkey")

TEST_DATA = TEST_DATA.drop(columns=removed_feat)

## 轉換時間格式

In [7]:
def LoctmToSec(loctm):
  sec = loctm % 100
  loctm //= 100
  min = loctm % 100
  loctm //= 100
  hour = loctm % 100
  return 3600 * hour + 60 * min + sec

In [8]:
DATA["loctm"] = DATA["loctm"].map(LoctmToSec)
TEST_DATA["loctm"] = TEST_DATA["loctm"].map(LoctmToSec)

## Unify Customer ID

In [9]:
CUSTOMER_DATA = pd.read_csv(CUSTOMER_DATA_PATH, header=None, delimiter=" ")
CUSTOMER_DATA = CUSTOMER_DATA.drop_duplicates()
CUSTOMER_IDX = CUSTOMER_DATA.set_index(0)[1].to_dict()

In [10]:
DATA["chid"] = DATA["chid"].map(CUSTOMER_IDX)
TEST_DATA["chid"] = TEST_DATA["chid"].map(CUSTOMER_IDX)

## 補足缺失的幣別

In [11]:
# 實付金額 flam1
# 消費地金額 csmam
money_cols = ["flam1", "csmcu", "csmam"]
money_train = DATA[~np.isnan(DATA["csmcu"]) & (DATA["csmam"] > 0)][money_cols]
money_test = TEST_DATA[~np.isnan(TEST_DATA["csmcu"]) & (TEST_DATA["csmam"] > 0)][money_cols]

money_data = pd.concat((money_train, money_test))
money_data["exchange_rate"] = money_data["flam1"] / money_data["csmam"]
grouped = money_data[["csmcu", "exchange_rate"]].groupby("csmcu")
avg_exchange_rate_table = grouped.mean()

In [12]:
def InferCsmcu(exchange_rate):
    return (avg_exchange_rate_table['exchange_rate'] - exchange_rate).abs().idxmin()

In [13]:
target_train = np.isnan(DATA["csmcu"]) & ~np.isnan(DATA["flam1"]) & (DATA["csmam"] > 0)
target_test = np.isnan(TEST_DATA["csmcu"]) & ~np.isnan(TEST_DATA["flam1"]) & (TEST_DATA["csmam"] > 0)
money_train = DATA[target_train]
money_test = TEST_DATA[target_test]

DATA.loc[target_train, 'csmcu'] = (money_train["flam1"] / money_train["csmam"]).map(InferCsmcu)
TEST_DATA.loc[target_test, 'csmcu'] = (money_test["flam1"] / money_test["csmam"]).map(InferCsmcu)

In [14]:
DATA = DATA.drop(columns='csmam')
TEST_DATA = TEST_DATA.drop(columns='csmam')

## 新增實付金額 / 交易金額 Ratio

In [15]:
# 實付金額 flam1
# 交易金額 conam
DATA["fc_ratio"] = (DATA["flam1"] / DATA["conam"])
DATA.loc[np.isnan(DATA['fc_ratio']), 'fc_ratio'] = 1.0
DATA = DATA.drop(columns='flam1')

TEST_DATA["fc_ratio"] = (TEST_DATA["flam1"] / TEST_DATA["conam"])
TEST_DATA.loc[np.isnan(TEST_DATA['fc_ratio']), 'fc_ratio'] = 1.0
TEST_DATA = TEST_DATA.drop(columns='flam1')

## 補足缺乏的國別資料
- 無 stocn 但有 scity 的資料，有機會使用現有的資料推出 stocn
- 有 stocn 無 scity 的資料和兩者皆無的資料就幫不上忙了

不過只要是台灣以外的地區我們都只看國別，所以只有 stocn = 0 但 scity = NaN 的 case 會需要另外處理

In [16]:
loc_cols = ['stocn', 'scity']
LOC_DATA = pd.concat((DATA[loc_cols], TEST_DATA[loc_cols]), ignore_index=True)

In [17]:
dedup_stocn_scity_pairs = LOC_DATA[~np.isnan(LOC_DATA['stocn']) & ~np.isnan(LOC_DATA['scity'])].drop_duplicates()
scity_to_stocn_map = dedup_stocn_scity_pairs.set_index('scity').to_dict()['stocn']

nan_rows = np.isnan(LOC_DATA['stocn'])
# The following is semantically equal to LOC_DATA[nan_rows]['stocn'] = ...
# However, it's safer and doesn't cause undefined behavior
LOC_DATA.loc[nan_rows, 'stocn'] = LOC_DATA.loc[nan_rows, 'scity'].map(scity_to_stocn_map)

## 轉換地點類別
NOTE: 需要重新編號，避免 scity 和 stocn 衝到
- stocn = 0, scity != NaN
    - scity (re-labeled scity)
- stocn = 0, scity = NaN
    - new category (number of unique scity)
    - 事實上在 training data 中，補足資料後就沒有這個 case 了
- stocn > 0
    - stocn (stocn + number of unique scity)
- stocn = NaN
    - NaN

In [18]:
_, idx = pd.factorize(LOC_DATA['scity'][LOC_DATA['stocn'] == 0])
# idx contains index of unique values excluding NaN
scity_unique_num = idx.shape[0]

train_tw_rows = DATA['stocn'] == 0
test_tw_rows = TEST_DATA['stocn'] == 0
scity_to_id = dict([(scity, id) for id, scity in enumerate(idx)])

DATA.loc[train_tw_rows, 'region'] = DATA.loc[train_tw_rows, 'scity'].map(scity_to_id)
TEST_DATA.loc[test_tw_rows, 'region'] = TEST_DATA.loc[test_tw_rows, 'scity'].map(scity_to_id)

DATA.loc[train_tw_rows & np.isnan(DATA['scity']), 'region'] = scity_unique_num
TEST_DATA.loc[test_tw_rows & np.isnan(TEST_DATA['scity']), 'region'] = scity_unique_num

DATA.loc[~train_tw_rows, 'region'] = DATA.loc[~train_tw_rows, 'stocn'] + scity_unique_num
TEST_DATA.loc[~test_tw_rows, 'region'] = TEST_DATA.loc[~test_tw_rows, 'stocn'] + scity_unique_num

In [19]:
DATA = DATA.drop(columns=loc_cols)
TEST_DATA = TEST_DATA.drop(columns=loc_cols)

## 分期
保留期數就好

In [20]:
DATA = DATA.drop(columns="insfg")
TEST_DATA = TEST_DATA.drop(columns="insfg")

## 新增特定欄位中各類別的 Fraud Ratio
除了自己分 bins 外，也可以放 numerical features 就好，讓 LightGBM 去試

In [21]:
FRAUD_DATA = DATA[DATA['label'] == 1]

In [22]:
# fraud ratio of each category in specified feature
def FraudRatio(column):
    data = DATA[column].value_counts()
    idx = data.index
    count = data.values

    ratio = [
        (FRAUD_DATA[column] == i).sum() / c
        # if c > 20 else np.nan
        for i, c in zip(idx, count)
    ]

    return pd.Series(ratio, index=idx).to_dict()

In [23]:
def FindBin(ratio, boundaries):
    if np.isnan(ratio):
        return np.nan
    # first bin is closed at both boundaries
    # other bins are open at left boundary and closed at right boundary
    if ratio == 0:
        return 1
    return np.searchsorted(boundaries, ratio, side="left")

In [24]:
mcc_fraud_ratio_map = FraudRatio("mcc")

mcc_fraud_ratio = DATA["mcc"].map(mcc_fraud_ratio_map)
DATA["mcc_fr"] = mcc_fraud_ratio

mcc_fraud_ratio = TEST_DATA["mcc"].map(mcc_fraud_ratio_map)
TEST_DATA["mcc_fr"] = mcc_fraud_ratio

In [25]:
region_fraud_ratio_map = FraudRatio("region")

region_fraud_ratio = DATA["region"].map(region_fraud_ratio_map)
DATA["region_fr"] = region_fraud_ratio

region_fraud_ratio = TEST_DATA["region"].map(region_fraud_ratio_map)
TEST_DATA["region_fr"] = region_fraud_ratio

In [26]:
chid_fraud_ratio_map = FraudRatio("chid")

chid_fraud_ratio = DATA["chid"].map(chid_fraud_ratio_map)
DATA["chid_fr"] = chid_fraud_ratio

chid_fraud_ratio = TEST_DATA["chid"].map(chid_fraud_ratio_map)
TEST_DATA["chid_fr"] = chid_fraud_ratio

In [27]:
DATA = DATA.drop(columns=["mcc", "region", "chid"])
TEST_DATA = TEST_DATA.drop(columns=["mcc", "region", "chid"])

## One-Hot Encoding

In [28]:
cat_feats = [
    'contp',
    'etymd',
    'ecfg',
    'bnsfg',
    'stscd',
    'ovrlt',
    'flbmk',
    'hcefg',
    'csmcu',
    'flg_3dsmk',
]

In [29]:
all_cat_data = pd.concat((DATA[cat_feats], TEST_DATA[cat_feats]))
encoded_cat_data = pd.get_dummies(all_cat_data, dummy_na=True, columns=cat_feats)

DATA = DATA.drop(columns=cat_feats)
TEST_DATA = TEST_DATA.drop(columns=cat_feats)

DATA =  pd.concat((DATA, encoded_cat_data.iloc[:DATA.shape[0]]), axis=1)
TEST_DATA = pd.concat((TEST_DATA, encoded_cat_data.iloc[DATA.shape[0]:]), axis=1)

## Deal with NaN in Numerical Features
NN 不接受 nan 的輸入

In [30]:
for col in DATA.columns:
    nan_count = DATA[col].isna().sum()
    if nan_count > 0:
        print(col, nan_count)

mcc_fr 4550
region_fr 600

In [31]:
for col in TEST_DATA.columns:
    nan_count = TEST_DATA[col].isna().sum()
    if nan_count > 0:
        print(col, nan_count)

mcc_fr 360
region_fr 86
chid_fr 7959

In [32]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

def ImputeData(data):
    imputed_data = imputer.fit_transform(data)
    imputed_data = pd.DataFrame(imputed_data, columns=data.columns)
    return imputed_data

In [33]:
DATA = ImputeData(DATA)

test_txkey = TEST_DATA["txkey"]
TEST_DATA = ImputeData(TEST_DATA.iloc[:, 1:])
TEST_DATA["txkey"] = test_txkey

## Export Data

In [34]:
DATA.to_csv('data/proc_training_nn.csv', header=True, index=None)
TEST_DATA.to_csv('data/proc_testing_nn.csv', header=True, index=None)